service: serverlesswp-wordpress-starter

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'

functions:
  requestHandler:
    handler: api/index.handler
    memorySize: 1024
    timeout: 15
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      DATABASE: 'testwpgi'
      USERNAME: 'wcaj0hlyzygbzygaa8jo'
      PASSWORD: 'pscale_pw_3ccJDg5Jw5U0ytbcPSJBjLBJKKfkWVCvhC8MfW6zcPv'
      HOST: 'aws.connect.psdb.cloud'
